### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by isaacmeira** [isaacmeira/SeniorChallenge#1]
TODO
Back-end

- [ ] Criar a migration do banco de dados via sequelize
- [ ] Conectar corretamente a migration às rotas do node
- [ ] Testar a condição npx sequelize db:migrate
- [ ] Implementar cadastro das solicitações
- [ ] Conectar o node ao angular

Front-end

- [ ] Criar Layout de requisição / Flexbox - Font Awesome
- [ ] Ajustar layout da equisição para Almoxarife
- [ ] Criar layout Setor Administrativo
- [ ] Consumir api e retornar

Extras

- [ ] Adicionar Sweet Alerts
- [ ] Adicionar transições
- [ ] Ajustar SEO
- [ ] Verificar se os inputs estão validados
- [ ] Minificar o Scss e o JS
